version: 2

project_name: teamcontext

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - main: ./cmd/teamcontext
    binary: teamcontext
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

brews:
  - name: teamcontext
    repository:
      owner: saeedalam
      name: homebrew-tap
    homepage: https://github.com/saeedalam/teamcontext
    description: "The Technical Memory That Outlives Everyone"
    license: MIT
    install: |
      bin.install "teamcontext"
    test: |
      system "#{bin}/teamcontext", "--help"
