package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/saeedalam/teamcontext/internal/storage"
	"github.com/saeedalam/teamcontext/pkg/types"
	"github.com/spf13/cobra"
)

var rulesFormat string

var generateRulesCmd = &cobra.Command{
	Use:   "generate-rules",
	Short: "Generate IDE agent rules from project knowledge",
	Long: `Generate .cursorrules, CLAUDE.md, or other IDE agent rule files
from the project's TeamContext knowledge base.

This reads all decisions, warnings, patterns, and project metadata to create
a system prompt that makes the IDE agent (Cursor, Claude Code, Windsurf)
automatically respect your team's conventions.

The generated rules instruct the agent to:
  - Check TeamContext context before writing code
  - Respect recorded decisions and warnings
  - Auto-capture new decisions from conversations
  - Follow established patterns

Formats:
  cursor    - .cursorrules file (default)
  claude    - CLAUDE.md file for Claude Code
  windsurf  - .windsurfrules file
  all       - Generate all formats

Examples:
  teamcontext generate-rules
  teamcontext generate-rules --format claude
  teamcontext generate-rules --format all`,
	Run: runGenerateRules,
}

func init() {
	println("[DEBUG] cli/generate_rules.go: init")
	generateRulesCmd.Flags().StringVarP(&rulesFormat, "format", "f", "cursor", "Output format: cursor, claude, windsurf, all")
	rootCmd.AddCommand(generateRulesCmd)
}

func runGenerateRules(cmd *cobra.Command, args []string) {
	tcDir, err := findTeamContextDirFromCwd()
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		fmt.Println("Run 'teamcontext init' first.")
		return
	}

	projectRoot := filepath.Dir(tcDir)
	jsonStore := storage.NewJSONStore(tcDir)

	content := buildRulesContent(jsonStore)

	switch rulesFormat {
	case "cursor":
		writeRulesFile(projectRoot, ".cursorrules", content)
	case "claude":
		writeRulesFile(projectRoot, "CLAUDE.md", content)
	case "windsurf":
		writeRulesFile(projectRoot, ".windsurfrules", content)
	case "all":
		writeRulesFile(projectRoot, ".cursorrules", content)
		writeRulesFile(projectRoot, "CLAUDE.md", content)
		writeRulesFile(projectRoot, ".windsurfrules", content)
	default:
		fmt.Printf("Unknown format: %s (use: cursor, claude, windsurf, all)\n", rulesFormat)
	}
}

func writeRulesFile(projectRoot, filename, content string) {
	path := filepath.Join(projectRoot, filename)

	// Check if file already exists
	if _, err := os.Stat(path); err == nil {
		// Read existing content to check for manual sections
		existing, err := os.ReadFile(path)
		if err == nil && !strings.Contains(string(existing), "# === TEAMCONTEXT AUTO-GENERATED") {
			fmt.Printf("  %s already exists and was not generated by TeamContext. Skipping.\n", filename)
			fmt.Printf("  To overwrite, delete the file first and re-run.\n")
			return
		}
	}

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		fmt.Printf("  Error writing %s: %v\n", filename, err)
		return
	}
	fmt.Printf("  Generated %s\n", path)
}

func buildRulesContent(jsonStore *storage.JSONStore) string {
	var b strings.Builder

	b.WriteString("# === TEAMCONTEXT AUTO-GENERATED ===\n")
	b.WriteString("# Regenerate with: teamcontext generate-rules\n")
	b.WriteString("# Do not edit the auto-generated sections manually.\n\n")

	// Project overview
	project, err := jsonStore.GetProject()
	if err == nil && project != nil {
		b.WriteString("# Project: " + project.Name + "\n\n")
		if project.Description != "" {
			b.WriteString(project.Description + "\n\n")
		}
		if len(project.Languages) > 0 {
			b.WriteString("**Languages:** " + strings.Join(project.Languages, ", ") + "\n\n")
		}
	}

	// TeamContext integration protocol
	b.WriteString("## TeamContext Integration Protocol\n\n")
	b.WriteString("You are connected to **TeamContext**, this project's long-term technical memory.\n")
	b.WriteString("TeamContext is available as an MCP server with tools for querying and recording knowledge.\n\n")

	b.WriteString("### 1. ALWAYS-ON CONTEXT CHECK\n\n")
	b.WriteString("Before writing or modifying code, you MUST:\n")
	b.WriteString("1. Call `get_context` with your intent and target files.\n")
	b.WriteString("2. If TeamContext returns **Decisions**, follow them or explain why you need to deviate.\n")
	b.WriteString("3. If TeamContext returns **Warnings**, explicitly state how you will avoid those pitfalls.\n")
	b.WriteString("4. If TeamContext returns **Patterns**, follow the established conventions.\n\n")

	b.WriteString("### 2. AUTO-CAPTURE PROTOCOL\n\n")
	b.WriteString("You are the team's scribe. Capture knowledge automatically:\n")
	b.WriteString("- If the user says \"let's use X instead of Y\" or makes an architectural choice, call `add_decision`.\n")
	b.WriteString("- If a build fails, a bug is found, or an approach doesn't work, call `add_warning`.\n")
	b.WriteString("- If you discover a repeated pattern in the codebase, call `add_pattern`.\n")
	b.WriteString("- Never ask the user to manually record knowledge. Just do it.\n\n")

	b.WriteString("### 3. EXPERT AWARENESS\n\n")
	b.WriteString("When modifying files, check `find_experts` to know who owns the code.\n")
	b.WriteString("Mention the expert if the change is significant: \"Sarah owns this module, following her patterns.\"\n\n")

	// Active decisions
	decisions, _ := jsonStore.GetDecisions()
	activeDecisions := filterActiveDecisions(decisions)
	if len(activeDecisions) > 0 {
		b.WriteString("## Active Decisions\n\n")
		b.WriteString("These are binding architectural decisions. Follow them unless explicitly overridden.\n\n")
		for _, d := range activeDecisions {
			b.WriteString(fmt.Sprintf("- **%s** — %s", d.Content, d.Reason))
			if d.Feature != "" {
				b.WriteString(fmt.Sprintf(" (Feature: %s)", d.Feature))
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Active warnings
	warnings, _ := jsonStore.GetWarnings()
	if len(warnings) > 0 {
		b.WriteString("## Warnings & Pitfalls\n\n")
		b.WriteString("Avoid these known issues:\n\n")
		limit := len(warnings)
		if limit > 20 {
			limit = 20
		}
		for _, w := range warnings[:limit] {
			severity := strings.ToUpper(w.Severity)
			if severity == "" {
				severity = "WARNING"
			}
			b.WriteString(fmt.Sprintf("- [%s] **%s** — %s\n", severity, w.Content, w.Reason))
		}
		b.WriteString("\n")
	}

	// Patterns
	patterns, _ := jsonStore.GetPatterns()
	if len(patterns) > 0 {
		b.WriteString("## Established Patterns\n\n")
		b.WriteString("Follow these patterns when writing new code:\n\n")
		for _, p := range patterns {
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", p.Name, p.Description))
			if len(p.Examples) > 0 {
				b.WriteString(fmt.Sprintf("  Example: `%s`\n", p.Examples[0]))
			}
		}
		b.WriteString("\n")
	}

	b.WriteString("## MCP Tools Reference\n\n")
	b.WriteString("Key tools available via TeamContext MCP server:\n")
	b.WriteString("- `get_context` — Get relevant knowledge before modifying code\n")
	b.WriteString("- `query` — Ask any question about the codebase\n")
	b.WriteString("- `check_compliance` — Validate code against decisions and patterns\n")
	b.WriteString("- `add_decision` — Record an architectural decision\n")
	b.WriteString("- `add_warning` — Record a pitfall to avoid\n")
	b.WriteString("- `add_pattern` — Record a coding pattern\n")
	b.WriteString("- `resume_context` — Load previous session state for a feature\n")
	b.WriteString("- `onboard` — Get structured project walkthrough\n")
	b.WriteString("- `find_experts` — Find who owns specific code areas\n")

	return b.String()
}

func filterActiveDecisions(decisions []types.Decision) []types.Decision {
	var active []types.Decision
	for _, d := range decisions {
		if d.Status == "" || d.Status == "active" {
			active = append(active, d)
		}
	}
	// Cap at 30 to keep rules file manageable
	if len(active) > 30 {
		active = active[:30]
	}
	return active
}
